logging:
  level:
    root: INFO
    com.payments: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.apache.kafka: WARN

management:
  endpoint:
    health:
      show-details: always
