spring:
  application:
    name: mock-bank-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful


logging:
  level:
    com.payments: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/mock-bank-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/mock-bank-service.%d{yyyy-MM-dd}.%i.log


bank:
  card:
    success-rate: 0.85
    min-latency-ms: 200
    max-latency-ms: 500
  upi:
    success-rate: 0.92
    min-latency-ms: 50
    max-latency-ms: 150
  net-banking:
    success-rate: 0.78
    min-latency-ms: 1000
    max-latency-ms: 3000


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: mock-bank-service
    description: Bank/card-network processing simulator
